# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: deepvariant/protos/resources.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='deepvariant/protos/resources.proto',
  package='learning.genomics.deepvariant',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\"deepvariant/protos/resources.proto\x12\x1dlearning.genomics.deepvariant\"\x95\x02\n\x0fResourceMetrics\x12\x11\n\thost_name\x18\x01 \x01(\t\x12\x1b\n\x13physical_core_count\x18\x02 \x01(\x05\x12\x19\n\x11\x63pu_frequency_mhz\x18\x03 \x01(\x01\x12\x17\n\x0ftotal_memory_mb\x18\x04 \x01(\x05\x12\x19\n\x11wall_time_seconds\x18\x05 \x01(\x01\x12\x1d\n\x15\x63pu_user_time_seconds\x18\x06 \x01(\x01\x12\x1f\n\x17\x63pu_system_time_seconds\x18\x07 \x01(\x01\x12\x1a\n\x12memory_peak_rss_mb\x18\x08 \x01(\x05\x12\x12\n\nread_bytes\x18\t \x01(\x03\x12\x13\n\x0bwrite_bytes\x18\n \x01(\x03\x62\x06proto3')
)




_RESOURCEMETRICS = _descriptor.Descriptor(
  name='ResourceMetrics',
  full_name='learning.genomics.deepvariant.ResourceMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host_name', full_name='learning.genomics.deepvariant.ResourceMetrics.host_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='physical_core_count', full_name='learning.genomics.deepvariant.ResourceMetrics.physical_core_count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_frequency_mhz', full_name='learning.genomics.deepvariant.ResourceMetrics.cpu_frequency_mhz', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_memory_mb', full_name='learning.genomics.deepvariant.ResourceMetrics.total_memory_mb', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='wall_time_seconds', full_name='learning.genomics.deepvariant.ResourceMetrics.wall_time_seconds', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_user_time_seconds', full_name='learning.genomics.deepvariant.ResourceMetrics.cpu_user_time_seconds', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cpu_system_time_seconds', full_name='learning.genomics.deepvariant.ResourceMetrics.cpu_system_time_seconds', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='memory_peak_rss_mb', full_name='learning.genomics.deepvariant.ResourceMetrics.memory_peak_rss_mb', index=7,
      number=8, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='read_bytes', full_name='learning.genomics.deepvariant.ResourceMetrics.read_bytes', index=8,
      number=9, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='write_bytes', full_name='learning.genomics.deepvariant.ResourceMetrics.write_bytes', index=9,
      number=10, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=347,
)

DESCRIPTOR.message_types_by_name['ResourceMetrics'] = _RESOURCEMETRICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ResourceMetrics = _reflection.GeneratedProtocolMessageType('ResourceMetrics', (_message.Message,), {
  'DESCRIPTOR' : _RESOURCEMETRICS,
  '__module__' : 'deepvariant.protos.resources_pb2'
  # @@protoc_insertion_point(class_scope:learning.genomics.deepvariant.ResourceMetrics)
  })
_sym_db.RegisterMessage(ResourceMetrics)


# @@protoc_insertion_point(module_scope)
